// <auto-generated />
namespace TestEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M2_Table2_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M2_Table2_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202009171843569_M2_Table2_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
